### ISSUE TITLE
Pretrained weights?

### ISSUE THREAD

**Issue by JohnnyRacer** [yinguobing/arcface#4]
Hi there, great job on the implementation of Arcface it's really well documentated! I haven't been able to find a link for the pretrained models however, are they avaliable or do I have to train them myself? Much appreicated.

**Comment by yinguobing** [comment]
The pretrained model was not archived properly. I'm afraid you have to train it yourself. 
Sorry about that.

**Comment by JohnnyRacer** [comment]
Thanks anyways. I've looked at the training code but didn't find anything clear on multi-GPU training, is it supported?

**Comment by yinguobing** [comment]
Sorry, it's not supported in this repo, since I only have one GPU installed in my PC.

By the way, the official ArcFace implementation supports multi-GPU training. If PyTorch is an acceptable option, please consider using the official code: https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch

**Comment by JohnnyRacer** [comment]
That's understandable, thanks a lot for the tip on the official Pytorch version.
